sudo: false
language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-23.0.1
    - android-23

before_install:
 - chmod +x gradlew

branches:
  only:
    - master

script:
    - ./gradlew clean assemble

