language: android
android:
  components:
    - build-tools-23.0.2
    - android-23

  licenses:
    - '.+'

script: ./gradlew clean assemble

before_install:
 - chmod +x gradlew

branches:
  only:
    - master

